version: '2.4'
services:
  web-local:
    #image: odoo:13.0
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    command: sh -c "./entrypoint-local.sh -u hotel,hotel_reservation -d bfl_me"
    depends_on:
      - db-local
    ports:
      - "8080:8080"

    environment:
      - VIRTUAL_HOST=bfl-erp.lvh.me
#      - VIRTUAL_PROTO= rpc
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=bfl-erp.lvh.me
      - LETSENCRYPT_EMAIL=mm@vimmoda.com
    volumes:
      - odoo-web-data-local:/var/lib/odoo
      - ./docker/local/odoo-local.conf:/etc/odoo/odoo-local.conf
      - ./5ra_addons:/mnt/extra-addons
  db-local:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data-local:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data-local:
  odoo-db-data-local:

networks:
  default:
    external:
      name: nginx-proxy