version: '2.4'
services:
  web-dev:
    #image: odoo:13.0
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    #command: sh -c "./entrypoint-dev.sh -u  -d odoo_5ra"
    depends_on:
      - db-dev
    ports:
      - "8069:8069"
    expose:
      - 8069
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.rule=HostRegexp(`{subdomain:[a-zA-Z0-9]+}.le-5ra.de`)"
        #- "traefik.http.routers.traefik-secure.service=fontend-vida"
        #- traefik.http.routers.fastapi.priority=1000
        #- "traefik.http.routers.fastapi.rule=HostRegexp(`{subdomain:*.le-5ra.de`)"
        #- "traefik.http.routers.fastapi.rule=Host(`ooodooo.le-5ra.de`)"
#      - "traefik.http.routers.fastapi.tls=true"
#      - "traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt"
        #- "traefik.frontend.rule=Host:odoo.le-5ra.de"
        #environment:
        #- VIRTUAL_HOST=le-5ra.de
#      - VIRTUAL_PROTO= rpc
#- VIRTUAL_PORT=8069
#     - LETSENCRYPT_HOST=le-5ra.de
        #- LETSENCRYPT_EMAIL=fm.maghraoui@gmail.com
    volumes:
      - odoo-web-data-testing:/var/lib/odoo
      - ./docker/dev/odoo-dev.conf:/etc/odoo/odoo-dev.conf
      - ./5ra_addons:/mnt/extra-addons
  db-dev:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data-testing:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data-testing:
  odoo-db-data-testing:

networks:
  default:
    external:
      name: traefik-proxy
